#theme: jekyll-theme-dinky
remote_theme : thiagorossener/jekflix-template

# Site settings
name: ARTIV
title:          ARTIV Tech Blog
description:    "DGIST ARTIV Tech blog"
url:            "https://dgist-artiv.github.io"

show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Staff
    url: /staff

categories_folder: category

markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

github_username: dgist-artiv

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
