#theme: jekyll-theme-dinky
remote_theme : thiagorossener/jekflix-template

# Site settings
name: ARTIV
title:          ARTIV Tech Blog
description:    "DGIST ARTIV Tech blog"
url:            "https://dgist-artiv.github.io"

show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Staff
    url: /staff.html

categories_folder: category

github_username: dgist-artiv

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
